version: "3"

services:
  database:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - database
