<?php

putenv('DISPLAY_ERRORS_DETAILS=' . false);

putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_HOST=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_DBNAME=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_USER=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PASSWORD=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PORT=');

putenv('JWT_SECRET_KEY=');
